namespace UnityEngine.XR.OpenXR.Features.Meta.Tests
{
    enum XrSemanticLabelMETA {
        XR_SEMANTIC_LABEL_UNKNOWN_META = 0,
        XR_SEMANTIC_LABEL_FLOOR_META = 1,
        XR_SEMANTIC_LABEL_CEILING_META = 2,
        XR_SEMANTIC_LABEL_WALL_FACE_META = 3,
        XR_SEMANTIC_LABEL_INNER_WALL_FACE_META = 4,
        XR_SEMANTIC_LABEL_INVISIBLE_WALL_FACE_META = 5,
        XR_SEMANTIC_LABEL_DOOR_FRAME_META = 6,
        XR_SEMANTIC_LABEL_WINDOW_FRAME_META = 7,
        XR_SEMANTIC_LABEL_MAX_ENUM_META = 0x7FFFFFFF
    }
}
